info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'
grails:
  serverURL: http://localhost:8080
  mail:
    host: smtp.gmail.com
    port: 465
    username: aloksingh4975@gmail.com
    password: jrvvmqmjkxxplsyy
    props:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.enable: true
      mail.debug: true
  default:
    from: aloksingh4975@gmail.com
  controllers:
    upload:
      maxFileSize: 10000000
      maxRequestSize: 10000000
  views:
    default:
      codec: html
    gsp:
      encoding: UTF-8
      htmlcodec: xml
      codecs:
        expression: html
        scriptlet: html
        taglib: none
        staticparts: none
  mime:
    disable:
      accept:
        header:
          userAgents:
          - Gecko
          - WebKit
          - Presto
          - Trident
    types:
      all: '*/*'
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      form: application/x-www-form-urlencoded
      html:
      - text/html
      - application/xhtml+xml
      js: text/javascript
      json:
      - application/json
      - text/json
      multipartForm: multipart/form-data
      pdf: application/pdf
      rss: application/rss+xml
      text: text/plain
      hal:
      - application/hal+json
      - application/hal+xml
      xml:
      - text/xml
      - application/xml
  plugin:
    console:
      enabled: true
  assets:
    enabled:
      true


dataSource:
  url: jdbc:oracle:thin:@localhost:1521/orclpdb1
  driverClassName: oracle.jdbc.OracleDriver
  dialect: org.hibernate.dialect.Oracle12cDialect
  username: linksharing_user
  password: 'linksharing1234'
  pooled: true
  jmxExport: true
  dbCreate: update

hibernate:
  allow_update_outside_transaction: true
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false

spring:
  h2:
    console:
      enabled: true
  servlet:
    multipart:
      max-file-size: 10000000
      max-request-size: 10000000

